### ISSUE TITLE
Problema con el singleton

### ISSUE THREAD

**Issue by Endermaiter** [Endermaiter/TrabajoProg3NetBeans#1]
El singleton funciona dentro de la librería pero no entre la libreria y el proyecto.

`con = Libreria.getInstance().establecerConexionBD()`

**Comment by DavidHermi** [comment]
Se ha solucionado el problema con el singlenton
Consulta la **[release v3.0](https://github.com/Endermaiter/TrabajoProg3NetBeans/releases/tag/v3.0)**
